services:
  - type: web
    name: giw
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: giw-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: giw-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: giw-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: giw-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: giw-db
          property: password

databases:
  - name: giw-db
    plan: free
    region: frankfurt
    databaseName: giw
    user: giw
